- src/backends/pprof.rs
- src/pyroscope.rs
- src/session.rs
- src/timer/sleep.rs
~Includes #11 and #10~ avoids all unwraps
> avoid almost all unwraps

- Cargo.toml
- src/error.rs
Improve discrimantive properties of the error type.
> use more features of `thiserror`

- Cargo.toml
- examples/internals-timer.rs
- src/error.rs
- src/pyroscope.rs
- src/session.rs
- src/timer/epoll.rs
- src/timer/kqueue.rs
- src/timer/mod.rs
- tests/agent.rs
- tests/session.rs
- tests/timer.rs
> allow configurable accumulation_cycle

- README.md
- src/lib.rs
I was surprised when I got the following error when I copied the crate reference from the document
```
error: no matching package found
searched package name: `pyroscope-pprofrs`
perhaps you meant:      pyroscope_pprofrs
location searched: registry `crates-io`
```
The  `pyroscope-pprofrs` in the document may be a typo.
https://crates.io/crates/pyroscope_pprofrs
> fix docs crate name

- Cargo.toml
- pyroscope_backends/pyroscope_pprofrs/Cargo.toml
- pyroscope_backends/pyroscope_pyspy/Cargo.toml
- pyroscope_backends/pyroscope_rbspy/Cargo.toml
- pyroscope_cli/Cargo.lock
- pyroscope_cli/Cargo.toml
- pyroscope_ffi/python/lib/Cargo.lock
- pyroscope_ffi/ruby/ext/rbspy/Cargo.lock
fixes: https://github.com/pyroscope-io/pyroscope-rs/issues/98
- Makes rustls certs the default
- Puts native certs under a new opt-in only feature
```
[features]
default = ["rustls-tls"]
rustls-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]
```
> Put openssl-sys under feature flag

- Cargo.toml
Bump the outdated deps. You can see it when you open the `Cargo.toml`.
> Update outdated deps

- src/timer/epoll.rs
I discovered a hang in the pyroscope agent, that is triggered when the `Timer` thread gets interrupted by a signal.
Instead of retrying the epoll_wait call, the `Timer` thread simply exits and no data is fed into the server.
This PR checks the `epoll_wait` error and retries the call if it gets `EINTR`.
> fix spurious exit when epoll_wait is interrupted by a signal

- Cargo.lock
- pyroscope_backends/pyroscope_pprofrs/Cargo.toml
Pyroscope is currently unusable with pprof-rs with the default stack unwinder: https://github.com/tikv/pprof-rs/issues/219
Frame-pointer seems to work, so let's expose it to end users
> pprof_rs: expose frame-pointer feature

- pyroscope_cli/README.md
Makes copy/paste easier if it's fixed.
> pyroscope_cli: README.md: Fix typo pyrsocope -> pyroscope

- Cargo.lock
- Cargo.toml
`names` has made questionable decision to depend on `clap` by the default which brings unnecessary dependencies for the library users: https://github.com/fnichol/names/blob/b5023b03e2339bf6e860bdcef20557ab81f3ec55/Cargo.toml#L21
> Avoid pulling in `clap` crate by the library

- Cargo.lock
- Cargo.toml
- examples/transform.rs
- src/backend/tests.rs
- src/backend/types.rs
- src/encode/folded.rs
- src/encode/pprof.rs
- src/pyroscope.rs
- src/session.rs
- src/timer/epoll.rs
- tests/session.rs
- tests/timer-epoll.rs
Sorry, the code was automatically formatted.
I don't know if it's an issue for you or no. Please let me know.
> fix clippy warnings

- src/encode/pprof.rs
Changing the `assert` macro to `assert_ne` macro would make it clearer. 
It's an insignificant, minor PR..
> fix: change to `assert_ne` macro

- Cargo.lock
- Cargo.toml
- pyroscope_cli/Cargo.toml
- pyroscope_cli/src/utils/app_config.rs
- pyroscope_cli/src/utils/error.rs
- src/error.rs
- src/pyroscope.rs
Fixes https://github.com/grafana/pyroscope-rs/issues/139 and includes a slight refactor to make this code more Rusty.
Not tested manually, had only ran unit tests.
> fix: replace json with serde_json 

- Cargo.lock
- pyroscope_backends/pyroscope_pprofrs/Cargo.toml
- pyroscope_backends/pyroscope_pprofrs/src/lib.rs
The original `pprof` crate is long abandoned and doesn't work with recent toolchains. There is a new `pprof2` crate that contains fixes and works with recent toolchains.
Fixes https://github.com/grafana/pyroscope-rs/issues/174
> fix: migrate to `pprof2` crate

- Cargo.lock
- pyroscope_backends/pyroscope_pyspy/Cargo.toml
- pyroscope_backends/pyroscope_rbspy/Cargo.toml
- pyroscope_ffi/python/lib/Cargo.toml
- pyroscope_ffi/ruby/ext/rbspy/Cargo.toml
see-also: https://github.com/benfred/py-spy/pull/642
see-also: https://github.com/benfred/py-spy/pull/713
Fixes https://github.com/grafana/pyroscope-rs/issues/168
also bumped `inferno` because `py-spy 0.4.0` requires `inferno 0.11.21`
> feat: bump py-spy to support python 3.12 and 3.13

- .github/workflows/ci-ffi-python.yml
- .github/workflows/ci-ffi-ruby.yml
- .github/workflows/release.yml
Draft - opening to trigger CI flow to assert impact
PR to fix CI and unblock deployments. 
**Issues:**
- `actions/upload-artifact` v2 is deprecated per https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
- **action:** bump to v4
- py3.12 is now supported due to https://github.com/grafana/pyroscope-rs/pull/181 
- **action:** add 3.12 to Python testing matrix
Ref:
https://github.com/grafana/pyroscope-rs/pull/181#issuecomment-2489076269
> Draft: Bump CICD actions/upload-artifact

- .github/workflows/ci-ffi-python.yml
- .github/workflows/ci-ffi-ruby.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- docker/Dockerfile.cli
- docker/Dockerfile.cli_builder
- docker/Dockerfile.manylinux2014_aarch64
- docker/Dockerfile.manylinux2014_x86_64
- docker/gem.Dockerfile
- docker/wheel.Dockerfile
- ffi.mk
- pyroscope_ffi/python/manylinux.sh
- pyroscope_ffi/python/setup.cfg
Attempting to fix github actions.
> Fix GitHub actions

- Cargo.lock
- Cargo.toml
- pyroscope_cli/Cargo.toml
- pyroscope_ffi/python/lib/Cargo.toml
- pyroscope_ffi/ruby/ext/rbspy/Cargo.toml
Our internal build static analysis tool flagged a few issues with the atty dependency that is pulled by pretty_env_logger 0.4.  Updating the dependency to the latest pretty_env_logger 0.5 drops the atty dependency and will eventually make our internal build happy.
This is a sample warning we are getting:
```
GHSA-g98v-hv3f-hcfr_atty
atty potential unaligned read
**source_type**: lockfile
**package_ecosystem**: crates.io
**vulnerabilitydetails**: On windows, `atty` dereferences a potentially unaligned pointer.
In practice however, the pointer won't be unaligned unless a custom global allocator is used.
In particular, the `System` allocator on windows uses `HeapAlloc`, which guarantees a large enough alignment.
A Pull Request with a fix has been provided over a year ago but the maintainer …
```
> Update pretty_env_logger version

- pyroscope_backends/pyroscope_pyspy/src/lib.rs
- pyroscope_ffi/python/lib/Cargo.toml
- pyroscope_ffi/python/lib/cbindgen.toml
- pyroscope_ffi/python/lib/include/pyroscope_ffi.h
- pyroscope_ffi/python/lib/src/lib.rs
- pyroscope_ffi/python/pyroscope/__init__.py
Helps to workaround https://github.com/grafana/pyroscope-rs/issues/197
Allow disabling the problematic line number collection with 
```python
line_no = pyroscope.LineNo.NoLine
```
> python: allow lines configuration

- .github/workflows/publish.yml
Most likely fixes the python publish issue, as it's due to a newer metadata version.
> fix: Update publish workflow

- pyroscope_ffi/python/pyroscope/__init__.py
The library currently uses the root logger, which can be problematic when you want to suppress these logs. This is particularly relevant for `pyroscope.shutdown()`. To address this, I have introduced the use of a private logger in `pyroscope.shutdown()`, and also in `pyroscope.configure()` for consistency.
> python: Use private logger instead of root logger

- Cargo.lock
- pyroscope_backends/pyroscope_rbspy/Cargo.toml
> chore: bump rbspy to 0.37
