grafana/pyroscope-rs

README.md
Changes orchasrate to orchestrate
=> fix: Fix typo

pyroscope_backends/pyroscope_pyspy/Cargo.toml, pyroscope_ffi/python/pyproject.toml, pyroscope_ffi/python/setup.cfg, pyroscope_ffi/python/setup.py
=> fix: bump pyspy for 3.11 support

pyroscope_cli/README.md
Found a broken link when I read the code.
=> Fix broken link

pyroscope_cli/Cargo.lock, pyroscope_cli/Cargo.toml, pyroscope_cli/src/cli/lib.rs, pyroscope_cli/tests/cli-ui/pyroscope_cli_completion_cmd_bash_cmd_stdout.toml, pyroscope_cli/tests/cli-ui/pyroscope_cli_completion_cmd_stdout.toml, pyroscope_cli/tests/cli-ui/pyroscope_cli_connect_cmd_stdout.toml, pyroscope_cli/tests/cli-ui/pyroscope_cli_exec_cmd_stdout.toml, pyroscope_cli/tests/cli-ui/pyroscope_cli_help_cmd_stdout.toml, pyroscope_cli/tests/cli-ui/pyroscope_cli_help_flag_stdout.toml, pyroscope_cli/tests/cli_ui.rs
part of https://github.com/pyroscope-io/pyroscope-rs/issues/92
Use trycmd to test the UI of CLI.
=> Add ui tests for CLI

Cargo.lock, pyroscope_backends/pyroscope_pyspy/src/lib.rs
=> fix(python): oncpu flag frong value

README.md
Hey, this commit contains a few typo fixes and grammar suggestions for you to consider.
=> Typos and grammar suggestions

Cargo.lock, Cargo.toml
https://github.com/seanmonstar/reqwest/releases/tag/v0.12.0
migrate to hyper v1
=> reqwest 0.12

.github/workflows/release.yml
=> fix: fork actions-upload-release-asset to use node16 to maybe fix release issues

.github/workflows/release.yml, ffi.mk, pyroscope_ffi/python/setup.cfg, pyroscope_ffi/python/setup.py, pyroscope_ffi/ruby/lib/pyroscope/version.rb
address https://github.com/grafana/pyroscope-rs/issues/161
=> fix: python wheel incorrect architecture on mac

CODEOWNERS
=> Make @grafana/pyroscope-team codeowners

.github/workflows/ci-ffi-python.yml, .github/workflows/release.yml
https://github.com/grafana/pyroscope-rs/issues/182
=> fix(ci): swtich arm runners

Cargo.lock
=> cargo update openssl

.github/workflows/ci-ffi-python.yml, .github/workflows/ci-ffi-ruby.yml, .github/workflows/publish.yml, .github/workflows/release.yml, Cargo.lock, Cargo.toml, docker/gem.Dockerfile, docker/wheel.Dockerfile, pyroscope_backends/pyroscope_pprofrs/Cargo.toml, pyroscope_backends/pyroscope_pyspy/Cargo.toml, pyroscope_backends/pyroscope_rbspy/Cargo.toml, pyroscope_cli/Cargo.toml, pyroscope_ffi/python/lib/Cargo.toml, pyroscope_ffi/ruby/ext/rbspy/Cargo.toml
note: cli tool does not compile, it was broken even before the PR. We'll need to fix this later.
=> chore: mass dependencies and toolchain upgrade

Cargo.lock, Cargo.toml, docker/wheel.Dockerfile
=> chore: disable unused unwind feature in python

Cargo.lock, Cargo.toml
https://github.com/grafana/py-spy/pull/1
=> chore: update pyspy to include linetable panic fix 

.github/workflows/ci-ffi-ruby.yml, Cargo.lock, pyroscope_backends/pyroscope_rbspy/Cargo.toml, pyroscope_ffi/ruby/Gemfile.lock, pyroscope_ffi/ruby/Makefile, pyroscope_ffi/ruby/lib/pyroscope/version.rb, pyroscope_ffi/ruby/scripts/tests/test.rb
fixes https://github.com/grafana/pyroscope-rs/issues/173
=> fix: bump rbspy to fix ruby 3.3.8, 3.4

docker/gem.Dockerfile
=> chore(ruby): remove libunwind from ruby

.github/workflows/publish.yml, .github/workflows/release.yml
I broke them with my previous zizmor commit
=> fix release workflows

pyroscope_ffi/python/setup.py
I have no idea what I am doing here. Not sure how it used to work, not sure why it broke, not sure why this fixes the build.
=> fix: maybe fix python build

Cargo.lock, Cargo.toml, pyroscope_backends/pyroscope_rbspy/Cargo.toml, pyroscope_ffi/ruby/Gemfile.lock, pyroscope_ffi/ruby/lib/pyroscope/version.rb
include this fix https://github.com/rbspy/rbspy/pull/396
=> fix(rbspy): premature oncpu exit

Cargo.lock, Cargo.toml, pyroscope_backends/pyroscope_rbspy/Cargo.toml
fix https://github.com/grafana/pyroscope-rs/issues/231
=> rbspy: remove fork, update dependency

src/session.rs
Help troubleshoot errors like https://github.com/grafana/pyroscope-rs/issues/235
Errors will look like this
```
2025-09-14T09:34:40.216Z ERROR Pyroscope::Session > Sending Session failed 400 {"code":"invalid_argument","message":"name: invalid service name: examp $$ le.basic: character is not allowed: ' '"}
```
=> fix: log error body if response is not successfull

src/session.rs
fixes https://github.com/grafana/pyroscope-rs/issues/230
Before
After
=> fix: do not create http clients every 10s

pyroscope_ffi/ffikit/src/lib.rs
fixes a panic that breaks request processing in rails if the bind failed:
thread '<unnamed>' panicked at pyroscope_ffi/ruby/ext/rbspy/src/lib.rs:291:64: called `Result::unwrap()` on an `Err` value: Io(Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: core::result::unwrap_failed
3: add_thread_tag
4: <unknown>
5: <unknown>
6: <unknown>
7: rbffi_CallFunction
8: <unknown>
9: vm_call_cfunc_with_frame_
at /usr/src/ruby/vm_insnhelper.c:3801:12
Related Issue: https://github.com/grafana/pyroscope-rs/issues/240
=> Catch and log failing to bind and connect to the unix domain socket
